import Head from 'next/head'
import Image from 'next/image'
import styles from 'src/styles/Home.module.css'
import { Header } from 'src/components/Header/index.jsx'
import { Main } from 'src/components/Main/index.jsx'
import { Footer } from 'src/components/Footer/index.jsx'
import { useCounter } from 'src/hooks/useCounter'
import { useInputArray } from 'src/hooks/useInputArray'
import { useBgLightBlue } from 'src/hooks/useBgLightBlue'

export default function Home() {

  //カスタムフックの呼び出し
  const { count, isShow, handleClick, toggleShow } = useCounter();
  const { text, array, handleChange, handleAdd } = useInputArray();

  useBgLightBlue();

  return (
    <div className={styles.container}>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header />

      <div className={styles.directionColumn}>

        {isShow ? <h1>{count}</h1> : null}
        <button onClick={handleClick}>ボタン</button>
        <button onClick={toggleShow}>{isShow ? "非表示" : "表示"}</button>

        <input type="text" value={text} onChange={handleChange} />
        <button onClick={handleAdd}>追加</button>
        <ul>
          {array.map((item) => {
            return (
              <li key={item}>{item}</li>
            )
          })}
        </ul>

      </div>

      <Main fileName={"about"} />
      
      <Footer />
    </div>
  )
}
