import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Header } from '../components/Header.jsx'
import { Main } from '../components/Main.jsx'
import { Footer } from '../components/Footer.jsx'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Main fileName={"about"} />
      
      <Footer />
    </div>
  )
}
